# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/chris/anaconda3/bin/conda' 'shell.zsh' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/chris/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/chris/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/chris/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run $(p10k configure) or edit ~/.p10k.zsh.
#[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

export PATH=$PATH:/usr/bin

ulimit -n 200000
ulimit -u 2048

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
eval "$(nodenv init -)"

bindkey -e # use the emacs keymap

autoload bashcompinit && bashcompinit
complete -C '/usr/local/bin/aws_completer' aws

# aliases
alias gencove-start-small="aws-vault exec chrisfriedline-mfa -- \
    bash -c 'echo starting && aws ec2 start-instances --instance-ids i-0a6f9f90d1c500c4f && echo waiting && aws ec2 wait instance-status-ok --instance-ids i-0a6f9f90d1c500c4f && echo ready'"
alias gencove-start-big="aws-vault exec chrisfriedline-mfa -- \
    bash -c 'echo starting && aws ec2 start-instances --instance-ids i-093dd897cedb62b9f && echo waiting && aws ec2 wait instance-status-ok --instance-ids i-093dd897cedb62b9f && echo ready'"
alias gencove-stop-small="aws-vault exec chrisfriedline-mfa -- aws ec2 stop-instances --instance-ids i-0a6f9f90d1c500c4f"
alias gencove-stop-big="aws-vault exec chrisfriedline-mfa -- aws ec2 stop-instances --instance-ids i-093dd897cedb62b9f"
alias gencove-ssh-small="aws-vault exec chrisfriedline-mfa -- ssh -i ~/.ssh/id_rsa_user_tools_gencove_chris.friedline ec2-user@i-0a6f9f90d1c500c4f"
alias gencove-ssh-big="aws-vault exec chrisfriedline-mfa -- ssh -i ~/.ssh/id_rsa_user_tools_gencove_chris.friedline ec2-user@i-093dd897cedb62b9f"
alias gencove-ssh-small-fwd="aws-vault exec chrisfriedline-mfa -- ssh -i ~/.ssh/id_rsa_user_tools_gencove_chris.friedline ec2-user@i-0a6f9f90d1c500c4f -L 18888:localhost:8888"
alias gencove-ssh-big-fwd="aws-vault exec chrisfriedline-mfa -- ssh -i ~/.ssh/id_rsa_user_tools_gencove_chris.friedline ec2-user@i-093dd897cedb62b9f -L 28888:localhost:8888"

[ -f "/Users/chris/.ghcup/env" ] && source "/Users/chris/.ghcup/env" # ghcup-env

eval "$(aws-vault --completion-script-zsh)"

autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit
eval "$(register-python-argcomplete dx | sed 's/-o default//')"

alias github_sema4="export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_sema4'"
alias github_diamondage="export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_cfriedline_diamondage'"
alias github_cfriedline="export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_chrismac'"

eval "$(starship init zsh)"